- name: Fixing Xilinx ISE For Ubuntu 16.04
  hosts: vm
  user: vagrant

  tasks:
  - name: Setting Default Shell To Bash
    shell: 'rm /bin/sh && ln -s /bin/bash /bin/sh'
    become: true

  - name: User LD_LIBRARY_PATH
    lineinfile:
        path: ~/.bashrc
        line: LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/lib/x86_64-linux-gnu:/lib64/:/lib/
        insertafter: #.*

  - name: Xilinx ISE LD_LIBRARY_PATH Fixes
    become: true
    copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
    loop:
        - { src: '../files/common-settings64.sh', dest: '/opt/Xilinx/14.7/ISE_DS/common/.settings64.sh' }
        - { src: '../files/edk-settings64.sh', dest: '/opt/Xilinx/14.7/ISE_DS/EDK/.settings64.sh' }
        - { src: '../files/ise-settings64.sh',  dest: '/opt/Xilinx/14.7/ISE_DS/ISE/.settings64.sh' }
