---
- name: Configure Xilinx ISE Desktop Entry
  hosts: vm
  user: vagrant

  tasks:
  - name: Pushing Bash Script Helper
    become: yes
    copy:
        src: '../files/run-ise.sh'
        dest: /usr/local/bin
        mode: 0755

  - name: Pushing Desktop Entry
    copy:
        src: '../files/Xilinx ISE.desktop'
        dest: /home/vagrant/Desktop
        owner: vagrant
        group: vagrant
        mode: 0755
