---
- name: Post Xilinx ISE Installation For Setup
  hosts: vm
  user: vagrant

- import_playbook: playbooks/user-basics.yml
- import_playbook: playbooks/xilinx-menu-item.yml
- import_playbook: playbooks/digilent-usb-drivers.yml
- import_playbook: playbooks/xilinx-usb-drivers.yml
