---
- name: Vagrant-Only Provisioning
  hosts: vm
  user: vagrant

  tasks:
  - name: Add User's SSH Key
    authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Update Packages
    become: true
    apt:
        upgrade: yes
        update_cache: yes

  - name: Install Desktop Environment
    become: true
    apt:
        name: ubuntu-desktop
        state: present

  - name: Install Virtualization Helpers
    become: true
    apt:
        name: "{{ item }}"
        state: present
    loop:
        - qemu-guest-agent
        - spice-vdagent
